env:
- GO111MODULE=on
before:
  hooks:
  - go mod tidy
  - go mod vendor
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
  - -trimpath
  ldflags:
  - -s -w
  - -X "github.com/PeerXu/meepo/pkg/lib/version.Version={{ .Version }}"
  - -X "github.com/PeerXu/meepo/pkg/lib/version.GoVersion={{ .Env.GOVERSION }}"
  - -X "github.com/PeerXu/meepo/pkg/lib/version.GitHash={{ .Commit }}"
  - -X "github.com/PeerXu/meepo/pkg/lib/version.Built={{ .CommitDate }}"
checksum:
  name_template: 'checksums.txt'
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
  - goos: windows
    format: zip
  files:
  - none*
release:
  # Same as for github
  # Note: it can only be one: either github, gitlab or gitea
  github:
    owner: PeerXu
    name: meepo
  draft: true
snapcrafts:
- name: meepo
  name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  summary: Connect to your service without public IP in p2p channel
  description: |
    Meepo help you to build your private network over Internet in easy way.
  grade: stable
  confinement: classic
  publish: true
  apps:
    meepo:
      command: meepo
brews:
- description: |
    Meepo help you to build your private network over Internet in easy way.
  tap:
    owner: PeerXu
    name: homebrew-tap
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  folder: Formula
  homepage: https://github.com/PeerXu/meepo
  license: MIT
  test: |
    system "#{bin}/meepo version"
  install: |
    bin.install "meepo"
