name: goreleaser

on:
  push:
    branchs:
    - main
    tags:
    - '*'
  pull_request:

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Set up Environment
        run: |
          echo "GOVERSION=$(go version|awk '{print $3}')" >> $GITHUB_ENV
      - name: Set up Snapcraft
        run: |
          sudo apt update
          sudo apt install -yq snapcraft
      - name: Cache Go modules
        uses: actions/cache@v2.1.4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Snapcraft Login
        if: success() && startsWith(github.ref, 'refs/tags/')
        env:
          SNAPCRAFT_LOGIN: ${{ secrets.SNAPCRAFT_LOGIN }}
        run: |
          snapcraft login --with <(echo "$SNAPCRAFT_LOGIN")
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true
      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            goreleaser release --rm-dist
          elif [[ $GITHUB_REF == refs/heads/main ]]; then
            goreleaser release --rm-dist --snapshot
          fi
