name: goreleaser

on:
  push:
    branchs:
    - main
    tags:
    - '*'
  pull_request:

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Set up Environment
        run: |
          echo "GOVERSION=$(go version|awk '{print $3}')" >> $GITHUB_ENV
      - name: Set up Snapcraft
        # HACK: the mkdirs are  a hack for https://bugs.launchpad.net/snapcraft/+bug/1889741
        run: |
          sudo snap install --classic snapcraft
          mkdir -p $HOME/.cache/snapcraft/download
          mkdir -p $HOME/.cache/snapcraft/stage-packages
      - name: Cache Go modules
        uses: actions/cache@v2.1.4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Snapcraft Login
        if: success() && startsWith(github.ref, 'refs/tags/')
        env:
          SNAPCRAFT_TOKEN: ${{ secrets.SNAPCRAFT_TOKEN }}
        run: |
          snapcraft login --with <(echo "$SNAPCRAFT_TOKEN")
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true
      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]
          then
            goreleaser release --rm-dist
          else
            goreleaser release --rm-dist --snapshot
          fi
